---
spring:
  application:
    name: employee-count-batch
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"

logging:
  level:
    root: info

mybatis:
  # FIXME 実装時にmapper.xmlのディレクトリをmapper-locationsに指定
  mapper-locations: api.management.task.infrastructure.mapper.*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    default-fetch-size: 1000
    default-statement-timeout: 20
    return-instance-for-empty-row: true

---
# -Dspring.profiles.activeを指定しなかった場合に実行される application.ymlの指定
spring:
  profiles:
    default: local