---
spring:
  datasource:
    # FIXME dockerの設定終わったら接続情報を修正 タスクAPIとは別でコンテナ建てるつもり
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3315/company_db
    username: user
    password: password

logging:
  level:
    web: DEBUG
    api.management.task.infrastructure.mapper: DEBUG