version: '3.3'
services:
  db:
    build: mysql
    image: company_db:0.0.1
    restart: always
    environment:
      MYSQL_DATABASE: company_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: 'Asia/Tokyo'
    ports:
      - "3315:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d

volumes:
  mysql-db:
    driver: local